### ISSUE TITLE
SyntaxError:  Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by generalpask** [ultrasecurity/webkiller#6]
Got this SyntaxError while trying to run webkiller. I'm not super familiar with python so I'm not sure what it means, but it could be an easy fix.

OS: Windows 10 1809

```
$ python webkiller.py
  File "webkiller.py", line 16
    print '\r'
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int '\r')?
```

**Comment by generalpask** [comment]
I'm going through and fixing these issues one by one and I'm starting to get the feeling that all of your print statements are broken.

**Comment by generalpask** [comment]
Update: I've now fixed all print statements and I get this:

```
$ py webkiller.py
Traceback (most recent call last):
  File "webkiller.py", line 4, in <module>
    from modules import *
  File "C:\Program Files\webkiller\modules\__init__.py", line 3, in <module>
    from colors import *
ModuleNotFoundError: No module named 'colors'
```

**Comment by vahidsabet** [comment]
> Update: I've now fixed all print statements and I get this:
> 
> ```
> $ py webkiller.py
> Traceback (most recent call last):
>   File "webkiller.py", line 4, in <module>
>     from modules import *
>   File "C:\Program Files\webkiller\modules\__init__.py", line 3, in <module>
>     from colors import *
> ModuleNotFoundError: No module named 'colors'
> ```

same issue
